# === CHEMINS UTILISES DANS L'ANALYSE DES BAMs/SNPs ===
# === USED PATHS IN THE BAMs/SNPs analysis ===

chemins:

# permet de sélectionner le chemin du rapport lorsque ce dernier n'est pas spécifié par l'utilisateur
# allows to select the report path when its not specified by the user
  dossier_rapports_par_defaut: "C:/Users/user/Desktop/Dossier_BAM/Analyseur_BamSnp"

# chemin du dossier où se trouve le fichier csv contenant les snp des patients
# path to folder containing the CSV File and patients SNP
  fichier_csv: "N:/PATH/TO/CSV FILE"

# chemin du dossier contenant les dossiers patients issus du séquençage
# path to the folder containing run seq patients folders
  dossier_bam: "\\\\PATH\\PATIENTS\\FOLDERS"

# chemin menant vers le tableau de concordance qui contient les snp de référence
# path to the concordance table with reference SNPs
  tableau_concordance: "N:/.../tableau_concordance.csv"

# chemin menant vers le logger de l'application
# path to executable log file
  log_file: "C:/Users/user/Desktop/Dossier_BAM/Analyseur_BamSnp"

# === PARAMETRES FIXES DANS LE TRAITEMENT DE L'ANALYSE ===
# === FIXED PARAMETERS DURING THE ANALYSIS ===

parametres:

# profondeur de lecture minimale
# minimal read depth
  profondeur_min: 15

# Nombre de SNPs a faible prodondeur autorisés avant de considérer que le patient est discordant
# Number of SNPs with low coverage depth allowed before a patient is considered discordant
  profondeur_autorisee: 5

# choix du seuil de confiance déterminant l'hétérozygotie/l'homozygotie
# selection of the confidence threshold used to determine heterozygosity/homozygosity
  seuil_heterozygotie: 0.75

# taux seuil défini pour considérer qu'un patient est discordant
# threshold rate defined to consider the patient as discordant
  taux_defini: 90

# Nom de la colonne contenant le nom du patient dans le fichier CSV
# Column name containing the patients name in the CSV File
  nom_colonne_samplename: "Sample Name"

# Nom colonne positions et chromosome du tableau de concordance
# Column name with chromosome and positions in the concordance table
  nom_colonne_position : "hg38"
  nom_colonne_chr : "Chr"
  nom_colonne_rang : "Rang"
